---
- name: Configure basic network settings on the servers 
  hosts: all 
  tasks: 
  - name: Copy network configuration file to the servers 
    ansible.builtin.template:
      src: network-interface.tmpl 
      dest: /root/network-script.sh 
      mode: '744'
    become: true # Elevate privileges for this task

  - name: Execute the network configuration script 
    shell: /root/network-script.sh > /root/network-script.log
  - name: Add route
    shell: /sbin/ip route replace {{ remote_subnet }} dev {{ if_name }}
  - name: Include the ntp role
    include_role:
      name: ntp


